import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { DshSkinMarketplace, DSH_SKIN_CATALOG_URL, parseDshSkinCatalog } from "../src/main/dshSkinMarketplace";

function response(body: unknown, status = 200) {
  const text = JSON.stringify(body);
  return {
    ok: status >= 200 && status < 300,
    status,
    headers: { get: (name: string) => name === "content-length" ? String(Buffer.byteLength(text)) : null },
    text: async () => text
  };
}

function skinCatalog(generatedAt = "2026-08-17T00:00:00.000Z") {
  return {
    schemaVersion: 1,
    generatedAt,
    skins: [{
      id: "demo.skin",
      name: { zh: "演示主题", en: "Demo theme" },
      author: "demo",
      description: "A visual theme",
      repo: "https://github.com/demo/skin",
      package: "demo-skin",
      tags: ["dark"],
      modes: ["dark"],
      install: { target: "github:demo/skin#1234567890123456789012345678901234567890", version: "1.0.0", commit: "1234567890123456789012345678901234567890" },
      compatibility: { dsh: "^0.1.0", platform: ["web"] },
      screenshots: ["https://example.com/theme.png"],
      review: { compatibility: "verified", preview: "verified", installation: "verified" },
      license: { code: "MIT", commercialUse: true },
      starsSnapshot: 42,
      releaseUpdatedAt: "2026-08-16T00:00:00.000Z"
    }]
  };
}

describe("DshSkinMarketplace", () => {
  it("parses the appearance catalog generated by the catalog repository", () => {
    const value = skinCatalog("2026-08-18T00:00:00.000Z") as any;
    value.themes = value.skins;
    delete value.skins;
    delete value.themes[0].releaseUpdatedAt;

    const parsed = parseDshSkinCatalog(value);
    expect(parsed.skins).toHaveLength(1);
    expect(parsed.skins[0]).toMatchObject({
      id: "demo.skin",
      updatedAt: "2026-08-18T00:00:00.000Z",
      repositoryUrl: "https://github.com/demo/skin"
    });
  });

  it("caches a validated catalog and retains it when a later refresh fails", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-"));
    const cachePath = join(root, "catalog.json");
    const fetcher = vi.fn()
      .mockResolvedValueOnce(response(skinCatalog()))
      .mockResolvedValueOnce(response({ error: "offline" }, 503));
    const market = new DshSkinMarketplace({ cachePath, webProfileDir: join(root, "web"), marketInstalled: () => false, fetcher, now: () => 100 });

    const fresh = await market.snapshot();
    expect(fetcher).toHaveBeenCalledWith(DSH_SKIN_CATALOG_URL, expect.anything());
    expect(fresh).toMatchObject({ catalogSource: "remote", skins: [{ id: "demo.skin", stars: 42 }], host: { marketInstalled: false, connected: false } });
    expect(JSON.parse(readFileSync(cachePath, "utf8"))).toMatchObject({ version: 1, skins: [{ id: "demo.skin" }] });

    const diskCacheFetcher = vi.fn();
    const reloaded = new DshSkinMarketplace({ cachePath, webProfileDir: join(root, "web"), marketInstalled: () => false, fetcher: diskCacheFetcher, now: () => 101 });
    expect(await reloaded.snapshot()).toMatchObject({ catalogSource: "cache", skins: [{ id: "demo.skin", stars: 42 }] });
    expect(diskCacheFetcher).not.toHaveBeenCalled();

    const cached = await market.snapshot(true);
    expect(cached.catalogSource).toBe("cache");
    expect(cached.catalogError).toContain("HTTP 503");
    expect(cached.skins).toHaveLength(1);
  });

  it("keeps installed and runtime-connected states separate", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-host-"));
    const fetcher = vi.fn(async (url: string) => url === DSH_SKIN_CATALOG_URL
      ? response(skinCatalog())
      : response({ skins: [{ skinId: "demo.skin", installation: "installed", activation: "active", installedVersion: "1.0.0", installedAt: null, updateAvailable: false }], restartAvailable: true, runningAgentCount: 0 }));
    const market = new DshSkinMarketplace({ cachePath: join(root, "catalog.json"), webProfileDir: join(root, "web"), marketInstalled: () => true, fetcher });

    const snapshot = await market.snapshot();
    expect(snapshot.host).toMatchObject({ connected: true, marketInstalled: true, restartAvailable: true, skins: [{ skinId: "demo.skin", activation: "active" }] });
  });

  it("reads the local theme library without the market controller", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-local-"));
    const webProfileDir = join(root, "web");
    const packageDir = join(webProfileDir, "node_modules", "demo-skin");
    const localPackageDir = join(webProfileDir, "node_modules", "local-skin");
    mkdirSync(packageDir, { recursive: true });
    mkdirSync(localPackageDir, { recursive: true });
    mkdirSync(join(webProfileDir, ".dsh-skin-market"), { recursive: true });
    writeFileSync(join(webProfileDir, "package.json"), JSON.stringify({ dependencies: { "demo-skin": "github:demo/skin#1234567890123456789012345678901234567890", "local-skin": "file:local-skin" } }));
    writeFileSync(join(packageDir, "package.json"), JSON.stringify({ version: "1.0.0", dsh: { client: {} } }));
    writeFileSync(join(localPackageDir, "package.json"), JSON.stringify({ name: "local-skin", version: "2.0.0", description: "Local only", dsh: { client: {} } }));
    writeFileSync(join(webProfileDir, ".dsh-skin-market", "state.json"), JSON.stringify({ version: 1, activeSkinId: "demo.skin", disabledSkinIds: [] }));
    const market = new DshSkinMarketplace({
      cachePath: join(root, "catalog.json"),
      webProfileDir,
      marketInstalled: () => false,
      fetcher: async () => response(skinCatalog())
    });

    const snapshot = await market.snapshot();
    expect(snapshot.host).toMatchObject({ connected: false, marketInstalled: false, skins: [{ skinId: "demo.skin", installation: "installed", activation: "active" }] });
    expect(snapshot.localSkins).toMatchObject([{ id: "local:local-skin", packageName: "local-skin", version: "2.0.0" }]);
  });

  it("preserves an unstarred bundled catalog entry as null", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-stars-"));
    const catalog = skinCatalog() as any;
    catalog.skins[0].repo = null;
    catalog.skins[0].starsSnapshot = null;
    const market = new DshSkinMarketplace({ cachePath: join(root, "catalog.json"), webProfileDir: join(root, "web"), marketInstalled: () => false, fetcher: async () => response(catalog) });
    await expect(market.snapshot()).resolves.toMatchObject({ skins: [{ repositoryUrl: null, stars: null }] });
  });

  it("forwards a same-origin mutation and polls it to completion", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-mutate-"));
    const fetcher = vi.fn(async (url: string, init?: RequestInit) => {
      if (url === DSH_SKIN_CATALOG_URL) return response(skinCatalog());
      if (url.endsWith("/install")) {
        expect(init?.headers).toMatchObject({ origin: "http://127.0.0.1:3080" });
        expect(JSON.parse(String(init?.body))).toMatchObject({ skin: { id: "demo.skin", packageName: "demo-skin" } });
        return response({ operationId: "op-1" }, 202);
      }
      if (url.endsWith("/operations/op-1")) return response({ phase: "done" });
      return response({ skins: [], restartAvailable: false });
    });
    const market = new DshSkinMarketplace({ cachePath: join(root, "catalog.json"), webProfileDir: join(root, "web"), marketInstalled: () => true, fetcher, pollDelay: async () => undefined });

    const result = await market.mutate({ skinId: "demo.skin", action: "install" });
    expect(result.ok).toBe(true);
    expect(fetcher).toHaveBeenCalledWith("http://127.0.0.1:3080/dsh-appearance-manager/operations/op-1", expect.anything());
  });

  it("marks activation as restart-required until DSH reloads the browser loader", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-activate-"));
    const fetcher = vi.fn(async (url: string) => {
      if (url === DSH_SKIN_CATALOG_URL) return response(skinCatalog());
      if (url.endsWith("/activate")) return response({ operationId: "op-2" }, 202);
      if (url.endsWith("/operations/op-2")) return response({ phase: "done" });
      return response({ skins: [{ skinId: "demo.skin", installation: "installed", activation: "active", installedVersion: "1.0.0", installedAt: null, updateAvailable: false }], restartAvailable: true });
    });
    const market = new DshSkinMarketplace({ cachePath: join(root, "catalog.json"), webProfileDir: join(root, "web"), marketInstalled: () => true, fetcher, pollDelay: async () => undefined });

    const result = await market.mutate({ skinId: "demo.skin", action: "activate" });
    expect(result).toMatchObject({ ok: true, browserRefreshRequired: true, snapshot: { host: { skins: [{ activation: "restart-required" }] } } });
  });

  it("does not install a third-party market when the built-in manager is unavailable", async () => {
    const root = mkdtempSync(join(tmpdir(), "dsh-skins-install-"));
    const installPlugin = vi.fn(async () => ({ ok: true, restartRequired: true }));
    const market = new DshSkinMarketplace({
      cachePath: join(root, "catalog.json"),
      webProfileDir: join(root, "web"),
      marketInstalled: () => false,
      fetcher: async () => response(skinCatalog()),
      installPlugin
    });

    const result = await market.installMarket();
    expect(result).toMatchObject({ ok: false, restartRequired: false });
    expect(installPlugin).not.toHaveBeenCalled();
  });
});
